### ISSUE TITLE
exe terminates after ~1minute

### ISSUE THREAD

**Issue by T5-R** [jamesbarnett91/tplink-energy-monitor#17]
Hey. First I want to say thanks for sharing this project!

I downloaded tplink-monitor-win.exe v0.7. It starts and detects the Plugs fine. I can access the webpage and see the monitoring etc. But after a minute or so the exe terminates and monitoring stops. It does not write a log file so I can't share that... I can't capture it on screen as it exits too fast.
I tried to set the log interval to 10sec to see if that was the cause, but seem slike the config file path is hardcoded:
`Error reading logger config. Reverting to defaults. SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadLogConfig (C:\snapshot\tplink-energy-monitor\services\data-logger.js:0:0)
    at Object.<anonymous> (C:\snapshot\tplink-energy-monitor\services\data-logger.js:0:0)`

![image](https://user-images.githubusercontent.com/31586106/49385366-8e669580-f71d-11e8-867f-4d78f194dd8b.png)

**Comment by jamesbarnett91** [comment]
Hey thanks for the report, a few other people have mentioned similar problems so I'll have a look into it.

**Comment by jamesbarnett91** [comment]
This issue might be fixed in the latest release (v0.8) as the log writing now happens synchronously rather than async, but I can't reproduce this issue so can't say for sure.
So hopefully its fixed, but if not I can look into it some more.
Thanks

**Comment by say1899** [comment]
> This issue might be fixed in the latest release (v0.8) as the log writing now happens synchronously rather than async, but I can't reproduce this issue so can't say for sure.
> So hopefully its fixed, but if not I can look into it some more.
> Thanks

Thanks James!

I just installed the windows executable v.08 and it worked. Great to see those graphs :)

**Comment by chrisprolsm** [comment]
I also have this problem where "error reading logger config .... blablabla"
also the print says "log directory path : "."" whether I leave "." in the json or change it to "/" or change it to "C:\TPLink Monitor" (with the json and exe in this folder)
In this last option, it seem to work, though it didn't when I have it changed to "C:\Program Files (x86)\TPLink Monitor" (with the json and exe in this subfolder)

All that being said, thanks a lot for sharing; Those graphs are really a lacking functionnalities from TP Link.
Last point : I second the functionnality wish of an additionnal graph to display daily/monthly cost as well as maybe a interface page for the config file. That would make it much easier to use.
