### ISSUE TITLE
Error messages!

### ISSUE THREAD

**Issue by CJcreativeUK** [jamesbarnett91/tplink-energy-monitor#46]
Does this recurring error message mean anything to anyone.
NPM on Ubuntu

Chris

`TCP Timeout
[HS110(UK) 02] device.send() Error: TCP Timeout
(node:13330) UnhandledPromiseRejectionWarning: Error: TCP Timeout
    at Timeout._onTimeout (/home/user/tplink-energy-monitor/node_modules/tplink-smarthome-api/lib/client.js:249:20)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:13330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1138)

TCP Timeout
[HS110(UK) 02] device.send() Error: TCP Timeout
(node:13330) UnhandledPromiseRejectionWarning: Error: TCP Timeout
    at Timeout._onTimeout (/home/user/tplink-energy-monitor/node_modules/tplink-smarthome-api/lib/client.js:249:20)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:13330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1139)
TCP Timeout

[HS110(UK) 02] device.send() Error: TCP Timeout
(node:13330) UnhandledPromiseRejectionWarning: Error: TCP Timeout
    at Timeout._onTimeout (/home/user/tplink-energy-monitor/node_modules/tplink-smarthome-api/lib/client.js:249:20)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:13330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1140)
`

**Comment by tayl** [comment]
Requests to the device are timing out. Is this consistent or only intermittent? Is something negative happening as a result of these errors?

**Comment by simf93** [comment]
I just had the same problem. It completely stopped updating and showed these timeout errors. Unplugged the thing and plugged it back in, now it works again. Weird.

**Comment by CJcreativeUK** [comment]
It seems to lose "contact" with the HS110 and stop logging
