### ISSUE TITLE
Error with Node + NPM through windows 10

### ISSUE THREAD

**Issue by liakjim** [jamesbarnett91/tplink-energy-monitor#64]
Hello. 
I had tplink-energy-monitor working fine until recently on my windows 10 with node and npm . 
Today i am unable to load because there is the following error according to log file, so i would like some help
[2020-03-16T07_57_00_087Z-debug.log](https://github.com/jamesbarnett91/tplink-energy-monitor/files/4336938/2020-03-16T07_57_00_087Z-debug.log)
 :

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tplink-monitor@0.0.1~prestart: tplink-monitor@0.0.1
6 info lifecycle tplink-monitor@0.0.1~start: tplink-monitor@0.0.1
7 verbose lifecycle tplink-monitor@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle tplink-monitor@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\liakj\tplink-energy-monitor\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\liakj\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\liakj\AppData\Local\Programs\Python\Python38\;C:\Users\liakj\AppData\Local\Microsoft\WindowsApps;C:\Users\liakj\AppData\Roaming\npm
9 verbose lifecycle tplink-monitor@0.0.1~start: CWD: C:\Users\liakj\tplink-energy-monitor
10 silly lifecycle tplink-monitor@0.0.1~start: Args: [ '/d /s /c', 'node ./app.js' ]
11 silly lifecycle tplink-monitor@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle tplink-monitor@0.0.1~start: Failed to exec start script
13 verbose stack Error: tplink-monitor@0.0.1 start: `node ./app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid tplink-monitor@0.0.1
15 verbose cwd C:\Users\liakj\tplink-energy-monitor
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error tplink-monitor@0.0.1 start: `node ./app.js`
22 error Exit status 1
23 error Failed at the tplink-monitor@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by liakjim** [comment]
Ok, i realized that i had another app listening to 3000port so i edited the app.js and choose another port, like 4000, i pressed localhost:4000 and boom, working app. 
Case closed.
